"""
Verified programme facts: loads the auto-generated facts file and renders it
as a compact prompt block.

Why this exists (hallucination fix):
Volatile core facts (tuition, deadlines, start dates, duration, format) were
previously extracted from retrieved chunks at query time via regex heuristics,
which could attribute values to the wrong programme. This module replaces that
with a single validated source of truth that is regenerated by the scraping
pipeline (see src/pipeline/update_programme_facts.py) — never edited by hand
and never guessed at query time.
"""
import json
import os
from datetime import date

from src.config import config
from src.utils.logging import get_logger

logger = get_logger('verified_facts')

FACTS_FILENAME = os.path.join('database', 'programme_facts.json')

_LABELS = {
    'de': {
        'language': 'Sprache',
        'start': 'Programmstart',
        'duration': 'Dauer',
        'structure': 'Struktur',
        'locations': 'Orte',
        'tuition': 'Studiengebühr',
        'first_deadline': '1. Bewerbungsfrist',
        'final_deadline': 'Finale Bewerbungsfrist',
        'advisor': 'Ansprechpartner/in',
        'cohort': 'Aktuelle Kohorte',
    },
    'en': {
        'language': 'Language',
        'start': 'Programme start',
        'duration': 'Duration',
        'structure': 'Structure',
        'locations': 'Locations',
        'tuition': 'Tuition fee',
        'first_deadline': 'First application deadline',
        'final_deadline': 'Final application deadline',
        'advisor': 'Advisor',
        'cohort': 'Current cohort',
    },
}


class VerifiedFacts:
    _data: dict | None = None
    _load_attempted: bool = False

    @classmethod
    def _facts_path(cls) -> str:
        return os.path.join(config.paths.DATA, FACTS_FILENAME)

    @classmethod
    def load(cls) -> dict | None:
        """Load and cache the facts file. Returns None when unavailable."""
        if cls._data is not None or cls._load_attempted:
            return cls._data
        cls._load_attempted = True
        path = cls._facts_path()
        try:
            with open(path, encoding='utf-8') as f:
                cls._data = json.load(f)
            logger.info(
                f"Loaded verified programme facts (generated_at="
                f"{cls._data.get('generated_at', 'unknown')}) from {path}"
            )
        except FileNotFoundError:
            logger.warning(f"No verified facts file found at {path}; prompt will not include facts block")
        except (json.JSONDecodeError, OSError) as e:
            logger.error(f"Failed to load verified facts from {path}: {e}")
        return cls._data

    @classmethod
    def reset_cache(cls) -> None:
        cls._data = None
        cls._load_attempted = False

    @staticmethod
    def _lang_value(value, language: str) -> str:
        """Resolve {'de': ..., 'en': ...} dicts to the selected language."""
        if isinstance(value, dict):
            return str(value.get(language) or value.get('en') or next(iter(value.values()), ''))
        return str(value)

    @staticmethod
    def _format_fee(fee) -> str:
        try:
            return f"CHF {int(fee):,}".replace(',', "'")
        except (TypeError, ValueError):
            return f"CHF {fee}"

    @classmethod
    def _render_programme(cls, prog: dict, language: str) -> str:
        labels = _LABELS.get(language, _LABELS['en'])
        lines = [f"### {prog.get('official_name', 'Unknown programme')}"]

        if prog.get('current_cohort'):
            lines.append(f"- {labels['cohort']}: {prog['current_cohort']}")
        if prog.get('language'):
            lines.append(f"- {labels['language']}: {cls._lang_value(prog['language'], language)}")
        if prog.get('programme_start'):
            lines.append(f"- {labels['start']}: {prog['programme_start']}")
        if prog.get('duration'):
            lines.append(f"- {labels['duration']}: {cls._lang_value(prog['duration'], language)}")
        if prog.get('structure'):
            lines.append(f"- {labels['structure']}: {cls._lang_value(prog['structure'], language)}")
        if prog.get('locations'):
            lines.append(f"- {labels['locations']}: {cls._lang_value(prog['locations'], language)}")

        tuition = prog.get('tuition_chf') or {}
        first = tuition.get('first_deadline') or {}
        final = tuition.get('final_deadline') or {}
        if first or final:
            parts = []
            if first:
                parts.append(
                    f"{labels['first_deadline']} {first.get('deadline', '?')}: "
                    f"{cls._format_fee(first.get('fee'))}"
                )
            if final:
                parts.append(
                    f"{labels['final_deadline']} {final.get('deadline', '?')}: "
                    f"{cls._format_fee(final.get('fee'))}"
                )
            lines.append(f"- {labels['tuition']}: " + " | ".join(parts))
            note = tuition.get('note')
            if note:
                lines.append(f"  ({cls._lang_value(note, language)})")

        advisor = prog.get('advisor') or {}
        if advisor.get('name'):
            contact_bits = [advisor['name']]
            if advisor.get('email'):
                contact_bits.append(advisor['email'])
            if advisor.get('phone'):
                contact_bits.append(advisor['phone'])
            lines.append(f"- {labels['advisor']}: " + ", ".join(contact_bits))

        return "\n".join(lines)

    @classmethod
    def render_prompt_block(cls, language: str = 'en') -> str:
        """
        Render the verified facts as a prompt section. Returns an empty string
        when no facts are available, so callers can append unconditionally.
        """
        data = cls.load()
        if not data or not data.get('programmes'):
            return ""

        language = language if language in _LABELS else 'en'
        generated_at = data.get('generated_at', 'unknown')
        today = date.today().isoformat()

        sections = [
            cls._render_programme(prog, language)
            for prog in data['programmes'].values()
        ]

        return (
            "\n\nVERIFIED PROGRAMME FACTS "
            f"(auto-generated from the official programme websites on {generated_at}; "
            f"today is {today}):\n\n"
            + "\n\n".join(sections)
            + "\n\nRULES FOR THESE FACTS:\n"
            "- These verified facts are the AUTHORITATIVE source for tuition fees, "
            "application deadlines, start dates, duration, structure, locations, "
            "programme language, and advisor contacts.\n"
            "- Prefer them over retrieved context for these categories. If retrieved "
            "chunks conflict with these facts, use these facts and do not mention the conflict.\n"
            "- Deadlines earlier than today's date have passed; say so and point to the "
            "next applicable deadline and fee.\n"
            "- For topics NOT covered here (curriculum details, admission requirements, "
            "rankings, USPs, alumni network), use the retrieval tool as before.\n"
            "- Never combine fees from different programmes into a range."
        )
